on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build

jobs:
  build-deploy:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
      NOAA_KEY: ${{secrets.NOAA_KEY}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: 'https://tbep-tech.r-universe.dev'
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          version: 1.3.450
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tbeptools
            any::tidyverse
            any::flextable
            any::patchwork
            any::here
            any::rmarkdown
            any::ggrepel
            any::knitr
            any::ftExtra
            any::ggspatial
            any::prettymapr
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
